# Copyright (c) 2022, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from .config_generator_interface import ConfigGeneratorInterface
from model_analyzer.config.run.run_config import RunConfig
from model_analyzer.config.generate.model_run_config_generator import ModelRunConfigGenerator


class RunConfigGenerator(ConfigGeneratorInterface):
    """
    Generates all RunConfigs to execute given a list of models
    """

    def __init__(self, config, models, client):
        """
        Parameters
        ----------
        config: ModelAnalyzerConfig
        
        models: List of ConfigModelProfileSpec
            The models to generate ModelRunConfigs for
            
        client: TritonClient
        """
        self._config = config
        self._models = models
        self._client = client

        # FIXME
        self._triton_env = models[0].triton_server_environment()
        self._curr_model_run_configs = [None for x in models]
        self._curr_generators = [None for x in models]

    def is_done(self):
        return    self._curr_generators[0] is not None \
              and all([gen.is_done() for gen in self._curr_generators])

    def set_last_results(self, measurements):
        for gen in self._curr_generators:
            gen.set_last_results(measurements)

    def next_config(self):
        """
        Returns
        -------
        RunConfig
            The next RunConfig generated by this class
        """

        yield from self._generate_subset(0)

    def _generate_subset(self, index):
        mrcg = ModelRunConfigGenerator(self._config, self._models[index],
                                       self._client)
        model_run_config_generator = mrcg.next_config()

        self._curr_generators[index] = mrcg

        while not mrcg.is_done():
            next_config = next(model_run_config_generator)
            self._curr_model_run_configs[index] = next_config

            if index == (len(self._models) - 1):
                yield (self._make_run_config())
            else:
                yield from self._generate_subset(index + 1)

    def _make_run_config(self):
        run_config = RunConfig(self._triton_env)
        for i in range(len(self._models)):
            run_config.add_model_run_config(self._curr_model_run_configs[i])
        return run_config
